[package]
name = "rebase"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["sync", "macros"] }

[dev-dependencies]
operation = { path = "../operation" }
text = { path = "../text" }
tokio = { version = "1", features = ["sync", "macros", "rt"] }

[lib]
path = "src/lib.rs"
