[package]
name = "peeker"
version = "0.1.0"
edition = "2021"

[dependencies]
himark = { path = "../../himark" }
imba = { path = "../../imba" }
skia-safe = { version = "0.99.0", features = ["textlayout"] }
text = { path = "../../text" }

[dev-dependencies]
himark = { path = "../../himark", features = ["test-support"] }
himarkdown = { path = "../himarkdown" }
hirust = { path = "../lang/hirust" }
