[package]
name = "peeker"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
terminals = { path = "../../terminals" }
locations = { path = "../../locations" }
ahp-locations = { path = "../../ahp-locations" }
hikit = { path = "../../hikit" }
documents = { path = "../../documents" }
ahp-session = { path = "../../ahp-session" }
ahp-wire = { path = "../../ahp-wire" }
ahp-chat = { path = "../../ahp-chat" }
himark = { path = "../../himark" }
editor = { path = "../../editor" }
imba = { path = "../../imba" }
skia-safe = { version = "0.153.3", features = ["textlayout"] }
text = { path = "../../text" }

[dev-dependencies]
himark = { path = "../../himark", features = ["test-support"] }
editor = { path = "../../editor" }
himarkdown = { path = "../himarkdown" }
hirust = { path = "../lang/hirust" }
