[package]
name = "hipowershell"
version = "0.1.0"
edition = "2021"

[dependencies]
editor = { path = "../../../editor" }
hisitter = { path = "../../../hisitter" }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
tree-sitter-powershell = "0.26.4"

[dev-dependencies]
imba = { path = "../../../imba" }
