[target.wasm32-unknown-emscripten]
linker = "emcc"
rustflags = [
    "-C",
    "panic=abort",
    "-C",
    "link-arg=-sUSE_WEBGL2=1",
    "-C",
    "link-arg=-sMIN_WEBGL_VERSION=2",
    "-C",
    "link-arg=-sMAX_WEBGL_VERSION=2",
    "-C",
    "link-arg=-sFULL_ES3=1",
    "-C",
    "link-arg=-sALLOW_MEMORY_GROWTH=1",
    "-C",
    "link-arg=-sASSERTIONS=1",
    "-C",
    "link-arg=-lwebsocket.js",
    "-C",
    "link-arg=-sSUPPORT_LONGJMP=emscripten",
    "-C",
    "link-arg=-sINITIAL_MEMORY=134217728",
]
