[package]
name = "ahp-chat"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ahp-locations = { path = "../ahp-locations" }
ahp-lsp = { path = "../ahp-lsp" }
ahp-types = "0.9"
canvas = { path = "../canvas" }
ahp-wire = { path = "../ahp-wire" }
documents = { path = "../documents" }
editor = { path = "../editor" }
hikit = { path = "../hikit" }
humantime = "2"
imba = { path = "../imba" }
myersdiff = { path = "../myersdiff" }
operation = { path = "../operation" }
rpds = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
skia-safe = { version = "0.153.3", features = ["textlayout"] }
text = { path = "../text" }

[features]
test-support = ["hikit/test-support"]

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
hikit = { path = "../hikit", features = ["test-support"] }
ahp-wire = { path = "../ahp-wire", features = ["test-support"] }
