[package]
name = "hisolidity"
version = "0.1.0"
edition = "2021"

[dependencies]
editor = { path = "../../../editor" }
hisitter = { path = "../../../hisitter" }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
tree-sitter-solidity = "1.2.13"

[dev-dependencies]
imba = { path = "../../../imba" }
