#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(cd ../.. && pwd)"
SKIA_BINDINGS_DIR="$ROOT/vendor/skia-bindings-0.99.0"
SKIA_SOURCE_TAG="$(sed -nE 's/^skia[[:space:]]*=[[:space:]]*"([^"]+)"$/\1/p' "$SKIA_BINDINGS_DIR/Cargo.toml")"
SKIA_HEADERS_DIR="$ROOT/target/skia-headers/$SKIA_SOURCE_TAG"

case "$(uname -m)" in
  arm64)
    MACOS_RUST_TARGET="aarch64-apple-darwin"
    MACOS_XCODE_ARCH="arm64"
    ;;
  x86_64)
    MACOS_RUST_TARGET="x86_64-apple-darwin"
    MACOS_XCODE_ARCH="x86_64"
    ;;
  *)
    echo "unsupported macOS architecture: $(uname -m)" >&2
    exit 1
    ;;
esac

ensure_rust_target() {
  if rustup target list --installed | grep -qx "$MACOS_RUST_TARGET"; then
    return
  fi

  echo "==> rustup target add $MACOS_RUST_TARGET"
  rustup target add "$MACOS_RUST_TARGET"
}

ensure_skia_headers() {
  if [[ -f "$SKIA_HEADERS_DIR/include/core/SkCanvas.h" \
    && -f "$SKIA_HEADERS_DIR/modules/skcms/skcms.h" ]]; then
    return
  fi

  [[ -n "$SKIA_SOURCE_TAG" ]] || {
    echo "could not determine the pinned Skia source revision" >&2
    exit 1
  }

  if [[ -d "$SKIA_HEADERS_DIR/.git" ]]; then
    git -C "$SKIA_HEADERS_DIR" sparse-checkout set include modules
    return
  fi

  echo "==> fetching Skia $SKIA_SOURCE_TAG headers for the Metal bridge"
  mkdir -p "$(dirname "$SKIA_HEADERS_DIR")"
  git clone --depth 1 --filter=blob:none --sparse --branch "$SKIA_SOURCE_TAG" \
    https://github.com/rust-skia/skia.git "$SKIA_HEADERS_DIR"
  git -C "$SKIA_HEADERS_DIR" sparse-checkout set include modules
}

resolve() {
  local target_flag="$1" lib_dir="$2" out="$3" qualifier="${4:-}" append="${5:-}" xcode_arch="${6:-}"
  echo "==> cargo build -p frontend-host --release $target_flag"
  ( cd "$ROOT" && cargo build -p frontend-host --release $target_flag >/dev/null )

  local SKIA EXTRA
  {
    read -r SKIA
    read -r EXTRA
  } < <( cd "$ROOT" && cargo build -p frontend-host --release $target_flag \
           --message-format=json 2>/dev/null | python3 -c "
import sys, json
out=None; extra=[]
for line in sys.stdin:
    try: m=json.loads(line)
    except Exception: continue
    if m.get('reason')=='build-script-executed' and 'skia-bindings' in m.get('package_id',''):
        out=m['out_dir']
        for l in m.get('linked_libs', []):
            if l.startswith('framework='): extra.append('-framework '+l.split('=',1)[1])
            elif l=='c++': extra.append('-lc++')
        break
assert out, 'no skia out_dir'
print(out+'/skia')
print(' '.join(extra))
")

  if [ -z "$append" ]; then
    cat > "$out" <<XC
// Generated by build.sh — do not edit. Links this build's exact skia.
HEADER_SEARCH_PATHS = \$(SRCROOT) \$(SRCROOT)/Sources/Shared/SkiaMetalBridge/include $SKIA_HEADERS_DIR
XC
    if [ -n "$xcode_arch" ]; then
      echo "ARCHS = $xcode_arch" >> "$out"
    fi
  fi
  cat >> "$out" <<XC
LIBRARY_SEARCH_PATHS$qualifier = $lib_dir $SKIA
OTHER_LDFLAGS$qualifier = $lib_dir/libhimark_api.a -lskparagraph -lskshaper -lskunicode_core -lskunicode_icu -lskia -lskia-bindings $EXTRA
XC
  echo "    wrote $out$qualifier (skia: $SKIA)"
}

cp "$ROOT/frontend/frontend-host/include/himark.h" ./himark.h
ACTION="${1:-gen}"
ensure_skia_headers
ensure_rust_target

export BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_ios="--sysroot $(xcrun --sdk iphoneos --show-sdk-path)"
export BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_ios_sim="--sysroot $(xcrun --sdk iphonesimulator --show-sdk-path) --target=arm64-apple-ios-simulator"

resolve "--target $MACOS_RUST_TARGET" "$ROOT/target/$MACOS_RUST_TARGET/release" Generated-macOS.xcconfig "" "" "$MACOS_XCODE_ARCH"

if [ "$ACTION" = "gen" ] || [ "$ACTION" = "ios" ]; then
  resolve "--target aarch64-apple-ios" "$ROOT/target/aarch64-apple-ios/release" Generated-iOS.xcconfig "[sdk=iphoneos*]"
  resolve "--target aarch64-apple-ios-sim" "$ROOT/target/aarch64-apple-ios-sim/release" Generated-iOS.xcconfig "[sdk=iphonesimulator*]" append
  {
    echo "ARCHS[sdk=iphoneos*] = arm64"
    echo "ARCHS[sdk=iphonesimulator*] = $MACOS_XCODE_ARCH"
  } >> Generated-iOS.xcconfig
fi
[ -f Generated-iOS.xcconfig ] || echo "// run ./build.sh ios to build the iOS target" > Generated-iOS.xcconfig

command -v xcodegen >/dev/null || { echo "install XcodeGen: brew install xcodegen"; exit 1; }
xcodegen generate
echo "generated himark.xcodeproj (targets: himark-macOS, himark-iOS)"

case "$ACTION" in
  mac)
    rm -rf "build/Build/Products/Release/himark-macOS.app/Contents/MacOS/web"
    xcodebuild -project himark.xcodeproj -scheme himark-macOS -configuration Release \
      -derivedDataPath build build | tail -5
    ( cd "$ROOT" && cargo build -p agent-host --release --target "$MACOS_RUST_TARGET" >/dev/null )
    APP="build/Build/Products/Release/himark-macOS.app"
    cp "$ROOT/target/$MACOS_RUST_TARGET/release/himark-agent-host" "$APP/Contents/MacOS/"
    if [ -d "$ROOT/target/web" ]; then
      rm -rf "$APP/Contents/Resources/web"
      mkdir -p "$APP/Contents/Resources"
      cp -R "$ROOT/target/web" "$APP/Contents/Resources/web"
    else
      echo "note: no target/web — build the page with apps/web/tools/build-web.sh first"
    fi
    codesign --force --sign - "$APP/Contents/MacOS/himark-agent-host" 2>/dev/null || true
    codesign --force --sign - "$APP" 2>/dev/null || true
    open "$APP" ;;
  ios)
    echo "iOS built for aarch64-apple-ios; select the himark-iOS scheme in Xcode to run on a device/simulator." ;;
esac
