[package]
name = "hiocaml"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
editor = { path = "../../../editor" }
hisitter = { path = "../../../hisitter" }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
tree-sitter-ocaml = "0.26.0"

[dev-dependencies]
imba = { path = "../../../imba" }
