[package]
name = "ahp-comments"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ahp-types = "0.9"
ahp-wire = { path = "../ahp-wire" }
comments = { path = "../comments" }
documents = { path = "../documents" }
editor = { path = "../editor" }
imba = { path = "../imba" }
rpds = "1"
serde_json = "1"
tracing = "0.1"
