[package]
name = "hitypescript"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
editor = { path = "../../../editor" }
hisitter = { path = "../../../hisitter" }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
tree-sitter-typescript = "0.23.2"
tree-sitter-javascript = "0.25.0"

[dev-dependencies]
text = { path = "../../../text" }
imba = { path = "../../../imba" }
