[package]
name = "hicode"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
himark = { path = "../../himark" }
imba = { path = "../../imba" }
text = { path = "../../text" }
skia-safe = { version = "0.99.0", features = ["textlayout"] }

[dev-dependencies]
himark = { path = "../../himark", features = ["test-support"] }
himark-ahp-ext-types = { path = "../../../protocol/ahp-ext-types" }
serde_json = "1"
