/* Copyright © 2026 JetBrains s.r.o. */
/* SPDX-License-Identifier: Apache-2.0 */

#ifndef HIMARK_H
#define HIMARK_H

#pragma once

/* Generated by cbindgen from himark-api — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define HIMARK_KEY_BACKSPACE 1

#define HIMARK_KEY_ENTER 2

#define HIMARK_KEY_LEFT 3

#define HIMARK_KEY_RIGHT 4

#define HIMARK_KEY_UP 5

#define HIMARK_KEY_DOWN 6

#define HIMARK_KEY_ESCAPE 7

#define HIMARK_KEY_TAB 8

#define HIMARK_KEY_HOME 9

#define HIMARK_KEY_END 10

#define HIMARK_KEY_PAGE_UP 11

#define HIMARK_KEY_PAGE_DOWN 12

#define HIMARK_KEY_DELETE 13

#define HIMARK_KEY_F1 20

#define HIMARK_KEY_CHAR_BASE 32

#define HIMARK_MOD_SHIFT 1

#define HIMARK_MOD_CONTROL 2

#define HIMARK_MOD_ALT 4

#define HIMARK_MOD_COMMAND 8

/**
 * No phase information: a legacy wheel tick, or a host that cannot
 * tell gestures apart.
 */
#define HIMARK_SCROLL_PHASE_NONE 0

#define HIMARK_SCROLL_PHASE_MAY_BEGIN 1

#define HIMARK_SCROLL_PHASE_BEGAN 2

#define HIMARK_SCROLL_PHASE_CHANGED 3

#define HIMARK_SCROLL_PHASE_ENDED 4

#define HIMARK_SCROLL_PHASE_MOMENTUM_BEGAN 5

#define HIMARK_SCROLL_PHASE_MOMENTUM_CHANGED 6

#define HIMARK_SCROLL_PHASE_MOMENTUM_ENDED 7

typedef struct HimarkEngine HimarkEngine;

typedef struct {
    uint32_t start;
    uint32_t length;
} HimarkRange;

typedef struct {
    const char *ptr;
    uintptr_t len;
} HimarkStr;

typedef struct {
    HimarkStr kind;
    HimarkStr authority;
    const HimarkStr *segments;
    uintptr_t segment_count;
} HimarkLocation;

typedef struct {
    void *ctx;
    void (*pick_files)(void *ctx, uint64_t request, uint64_t window);
    void (*pick_save)(void *ctx, uint64_t request, const char *suggested, uintptr_t suggested_len);
    void (*fetch_document)(void *ctx, uint64_t request, const HimarkLocation *location);
    void (*store_document)(void *ctx,
                           uint64_t request,
                           const HimarkLocation *location,
                           const char *text,
                           uintptr_t text_len);
    void (*list_directory)(void *ctx, uint64_t request, const HimarkLocation *location);
    void (*subscribe)(void *ctx, uint64_t request, const HimarkLocation *location);
    void (*unsubscribe)(void *ctx, uint64_t subscription);
    void (*set_clipboard)(void *ctx, const char *text, uintptr_t text_len);
} HimarkHostCallbacks;

typedef struct {
    float x;
    float y;
    float width;
    float height;
} HimarkRect;

bool himark_agent_host_autostart(void);

HimarkEngine *himark_create(void);

uint64_t himark_add_window(HimarkEngine *engine);

void himark_destroy(HimarkEngine *engine);

void himark_set_wake(HimarkEngine *engine, void (*callback)(void*), void *context);

void himark_set_effect_wake(HimarkEngine *engine, void (*callback)(void*), void *context);

void himark_run_pending(HimarkEngine *engine);

bool himark_drain(HimarkEngine *engine);

bool himark_draw(HimarkEngine *engine,
                 uint64_t window,
                 void *canvas,
                 float width,
                 float height,
                 float _scale);

bool himark_key_down(HimarkEngine *engine, uint64_t window, uint32_t key, uint32_t mods);

bool himark_text_input(HimarkEngine *engine, uint64_t window, const char *utf8, uintptr_t len);

uintptr_t himark_copy(HimarkEngine *engine, uint64_t window, char *out, uintptr_t cap);

uintptr_t himark_cut(HimarkEngine *engine, uint64_t window, char *out, uintptr_t cap);

bool himark_paste(HimarkEngine *engine, uint64_t window, const char *utf8, uintptr_t len);

bool himark_text_input_replacing(HimarkEngine *engine,
                                 uint64_t window,
                                 const char *utf8,
                                 uintptr_t len,
                                 HimarkRange replacement);

float himark_toolbar_height(HimarkEngine *engine);

bool himark_mouse_drag(HimarkEngine *engine, uint64_t window, float x, float y, uint32_t mods);

bool himark_mouse_move(HimarkEngine *engine, uint64_t window, float x, float y);

bool himark_mouse_up(HimarkEngine *engine, uint64_t window, float x, float y);

bool himark_mouse_left(HimarkEngine *engine, uint64_t window);

bool himark_mouse_down(HimarkEngine *engine,
                       uint64_t window,
                       float x,
                       float y,
                       uint32_t mods,
                       uint32_t click_count);

bool himark_scroll(HimarkEngine *engine,
                   uint64_t window,
                   float x,
                   float y,
                   float _delta_x,
                   float delta_y);

bool himark_scroll_phased(HimarkEngine *engine,
                          uint64_t window,
                          float x,
                          float y,
                          float delta_x,
                          float delta_y,
                          uint32_t phase);

bool himark_animation_tick(HimarkEngine *engine, double now_ms);

bool himark_perform_command(HimarkEngine *engine, uint64_t window, const char *id);

void himark_set_chrome_clearance(HimarkEngine *engine, float width);

void himark_set_host(HimarkEngine *engine, HimarkHostCallbacks callbacks);

bool himark_host_picked(HimarkEngine *engine,
                        uint64_t request,
                        const HimarkLocation *locations,
                        uintptr_t count);

bool himark_host_picked_folder(HimarkEngine *engine,
                               uint64_t request,
                               const HimarkLocation *location);

bool himark_host_fetched(HimarkEngine *engine,
                         uint64_t request,
                         const char *text,
                         uintptr_t text_len);

bool himark_host_subscribed(HimarkEngine *engine, uint64_t request, uint64_t subscription);

bool himark_file_changed(HimarkEngine *engine, uint64_t subscription);

bool himark_host_stored(HimarkEngine *engine, uint64_t request, bool stored);

bool himark_host_listed(HimarkEngine *engine,
                        uint64_t request,
                        const HimarkLocation *entries,
                        uintptr_t count);

bool himark_open_document(HimarkEngine *engine,
                          uint64_t window,
                          const char *name,
                          uintptr_t name_len,
                          const char *utf8,
                          uintptr_t len,
                          bool primary);

void himark_open_demo(HimarkEngine *engine, uint64_t window);

void himark_open_demo_wall(HimarkEngine *engine, uint64_t window);

bool himark_has_text_focus(HimarkEngine *engine, uint64_t window);

bool himark_has_marked_text(HimarkEngine *engine, uint64_t window);

bool himark_set_marked_text(HimarkEngine *engine,
                            uint64_t window,
                            const char *utf8,
                            uintptr_t len,
                            HimarkRange selected,
                            bool has_replacement,
                            HimarkRange replacement);

bool himark_unmark_text(HimarkEngine *engine, uint64_t window);

bool himark_marked_range(HimarkEngine *engine, uint64_t window, HimarkRange *out);

bool himark_selected_range(HimarkEngine *engine, uint64_t window, HimarkRange *out);

bool himark_set_selected_range(HimarkEngine *engine, uint64_t window, HimarkRange range);

bool himark_document_length(HimarkEngine *engine, uint64_t window, uint32_t *out);

bool himark_reveal_selection(HimarkEngine *engine, uint64_t window);

uintptr_t himark_selection_rects(HimarkEngine *engine,
                                 uint64_t window,
                                 HimarkRange range,
                                 HimarkRect *out,
                                 uintptr_t cap);

bool himark_first_rect(HimarkEngine *engine, uint64_t window, HimarkRange range, HimarkRect *out);

int64_t himark_char_index_at(HimarkEngine *engine, uint64_t window, float x, float y);

uintptr_t himark_substring(HimarkEngine *engine,
                           uint64_t window,
                           HimarkRange range,
                           char *out,
                           uintptr_t cap);

#endif  /* HIMARK_H */
